// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qygezerszypradpehess.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5Z2V6ZXJzenlwcmFkcGVoZXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzM0NjQsImV4cCI6MjA2MDAwOTQ2NH0.SWCOOz-SDn900MPFGPlFxtNWPvAVy_10zwh56Fq3KqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);